### PR TITLE
Updated the sample query to match documentation updates

### PR DESCRIPTION
**Pull request by jmostella**
* average-tip-per-mile-pipeline.asaql added
* deployresources.json replaced query with paramater
* README.md updated

### CODE REVIEW

**Review by ferantivero — APPROVED** [review]
LGTM 🚀 | huge thanks for this contribution @jmostella

**Comment by jmostella** [comment]
@ferantivero Hi can this be merged?

**Comment by ferantivero** [comment]
> @ferantivero Hi can this be merged?

just merged @jmostella thanks again!

**Comment by jmostella** [comment]
@ferantivero no problem happy to help out! We made good use of this sample on our project.

**Pull request merged**
